### ISSUE TITLE
You're discord server invite was invalid

### ISSUE THREAD

**Issue by BaksoKeras** [EastArctica/JS-Plugins#12]
pls i wanna join your discord. i have a chemistry test in 2 hours pls help man

**Comment by darvd29** [comment]
Same, the invite link does not work

**Comment by EastArctica** [comment]
Updated! Thanks for telling me.

**Comment by Nisha2004** [comment]
Parce necesito su discordia, para mis exámenes plis, ayudadme en eso:(

**Comment by EastArctica** [comment]
Invite link works fine for me, what's your discord?
