### ISSUE TITLE
unreleased scripts?

### ISSUE THREAD

**Issue by orangemn6** [EastArctica/JS-Plugins#16]
Can you please add the unreleased scripts to the extension? If it is not possible, how would I run the gimkit scripts? I am using the chromium browser on ubuntu 20.04

**Comment by EastArctica** [comment]
Sorry but none of the unreleased scripts are meant to go public. They are unreleased for a reason. The gimkit isn't working, and the kahoot was a debug build that is meant for debugging/exploring kahoot challenge internals.
